### ISSUE TITLE
 train melgan

### ISSUE THREAD

**Issue by liu-x-p** [houwenxin/zerospeech2020#1]
Thanks for sharing your code. I have a question when running your code.
When training the melgan which is used to synthesis speech, there is a parameter **--load_vqvae [path-to-vqvae-ckpts]**, how should I set it? I try to give the path to pretained model and also try 'True', but both are wrong.
**trainer.py: error: unrecognized arguments: ./model1/model-vqvae-5-148-744-True.pt**
**trainer.py: error: unrecognized arguments: True**

**Comment by houwenxin** [comment]
Thanks for your comments.

Please try this command:
python trainer.py --mode melgan --load_vqvae True --pretrained_vqvae [path-to-vqvae-ckpts] --language [english/surprise] --ckpt_path [path-to-save-model] --datadir [path-to-the-root-dir-of-dataset]

**Comment by liu-x-p** [comment]
@houwenxin Thanks for reply. I didn't notice the parameter **--pretrained_vqvae**.
