### ISSUE TITLE
melgan

### ISSUE THREAD

**Issue by liu-x-p** [houwenxin/zerospeech2020#2]
Hi, I have a problem when I train the melgan, the best model will always be the first epoch's model. Then I check the log and find it seems can't convergence.
![微信图片_20200824091255](https://user-images.githubusercontent.com/58974386/90994103-25f2d280-e5ea-11ea-867e-6c1e4def8acd.jpg)
Lr of melgan is 2e-4 which is the same as your hps, how to solve this problem?

**Comment by houwenxin** [comment]
Is your reconstruction loss decreasing? In my experiments, the reconstruction loss was able to converge. Maybe you could set **mel_error_weight** to 5e-1 to force converging.

**Comment by liu-x-p** [comment]
@houwenxin I restart another training for it, it works now. By the way, during my training for melgan, the training epoch is not the number as hyper-parameter 'melgan_epochs', and it seems to be same with 'vqvae_epochs'.
