### ISSUE TITLE
ABX

### ISSUE THREAD

**Issue by liu-x-p** [houwenxin/zerospeech2020#3]
Hi.
I'm trying to change the model based on your code. But when I run the ZS20 evaluate code to get the ABX score, I found that after hundreds of epochs training for the melgan, the ABX stays the same. Do you have this problem in your work?

**Comment by houwenxin** [comment]
Thanks for your comment. Actually, ABX score is to evaluate the quality of "discovered word unit" i.e. encoding, it is decided by the VQ-VAE model. Maybe you can attempt to improve the first-stage training.

**Comment by liu-x-p** [comment]
@houwenxin Thank you! Then maybe I can just train the melgan for one epoch, just to check my VQ-VAE model' performance?

**Comment by houwenxin** [comment]
Yes, you can try that.
